openapi: "3.0.0"
info:
  title: Governance Tutorial API
servers:
  - url: https://production.test.com/
    description: production environment

paths:
  /invoices:
    get:
      description: op-description
      responses:
        "200":
          description: teapot
          content:
            application/json:
              schema:
                type: object
        "429":
          description: too many requests
          content:
            application/json:
              schema:
                type: string